ci:
  # Skip hooks requiring `just` to be installed
  skip: [codespell, fmt, clippy]
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: "snap"
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: codespell
        name: Check for misspellings
        description: Checks for common misspellings in text files
        language: system
        entry: just spellcheck
        types: [text]
        exclude_types: [image]
        pass_filenames: false
      - id: fmt
        name: Format files
        description: Format files with cargo fmt
        language: system
        entry: just fmt
        types: [rust]
      - id: clippy
        name: Lint code
        description: Lint rust sources
        language: system
        entry: just clippy
        types: [rust]
        pass_filenames: false
