[workspace]
members = ["pacbot", "pacbot_discord", "pacbot_github", "libpacbot"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
libpacbot = { path = "libpacbot" }
pacbot_github = { path = "pacbot_github" }
pacbot_discord = { path = "pacbot_discord" }
reqwest = { version = "0.11.16", features = ["json", "rustls-tls"] }
poise = "0.5.3"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
serde = "1.0.160"
serde_json = "1.0.96"
flume = "0.10.14"

[profile.release]
lto = true
strip = true
panic = "abort"
