[package]
name = "pacbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.12", features = ["json", "rustls-tls"] }
dotenv_codegen = "0.15.0"
poise = "0.4.1"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde = "1.0.147"
serde_json = "1.0.87"
