name: Publish Production Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PUBLISH_PACKAGE_PAT }}

    - name: Install DockerSlim
      run: |
        curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -

    - name: Build Docker Images
      run: |
        docker build --network=host -t pacbot .
        yes | docker-slim build --target pacbot --tag pacbot --http-probe=false
        docker tag pacbot ghcr.io/pacstall/pacbot:latest
    - name: Push Images
      run: |
        docker push "ghcr.io/pacstall/pacbot:latest"
